use_gpu: true

run:
    output_dir: predictions
    predict_on_data_partition: test

defaults:
    - data: qe.vi_en

system:
    load: best_model.torch

    batch_size: 16
    num_data_workers: 0

    model:
        outputs:
            word_level:
                target: false
                gaps: false
                source: false
            sentence_level:
                hter: true
